name: Deploy to Fly.io

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Simplified workflow - focus only on deployment
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy to Fly.io
        run: |
          echo "Deploying to app offshore-rapport"
          flyctl deploy --remote-only --app offshore-rapport
          echo "Deployment completed"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}