name: Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Verify package-lock.json
      run: |
        if [ ! -f "package-lock.json" ]; then
          echo "package-lock.json not found! Creating it..."
          npm install --package-lock-only
          git add package-lock.json
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "Auto-generate package-lock.json [skip ci]"
          git push
        fi
      
    - name: Lint JavaScript
      run: npm run lint --no-fix
      continue-on-error: true
      
    - name: Validate HTML
      run: npm run validate
      continue-on-error: true
      
    - name: Check for valid JSON
      run: |
        npx jsonlint -q data/articles.json